loggers to check cicd var

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -33,11 +33,26 @@ deploy:
   stage: deploy
   image: alpine:latest
   before_script:
-    - apk add --no-cache openssh
+    - apk add --no-cache openssh-client
     - mkdir -p ~/.ssh
-    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
+    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
     - chmod 600 ~/.ssh/id_ed25519
-    - ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
+    - |
+      if [ -z "$EC2_HOST" ]; then
+        echo "ERROR: EC2_HOST is not set"
+        exit 1
+      fi
+    - |
+      if [ -z "$EC2_USER" ]; then
+        echo "ERROR: EC2_USER is not set"
+        exit 1
+      fi
+    - |
+      if [ -z "$SSH_PRIVATE_KEY" ]; then
+        echo "ERROR: SSH_PRIVATE_KEY is not set"
+        exit 1
+      fi
+    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
 
   script:
     - scp ServiceApp/target/*.jar $EC2_USER@$EC2_HOST:/opt/serviceapp/serviceapp.jar
